spring:
  application:
    name: zuul

server:
  port: 8090

zuul:
  prefix: /api
  routes:
    products:
      path: /products/**
      stripPrefix: false
      serviceId: product-service
    audits:
      path: /audits/**
      stripPrefix: false
      serviceId: audit-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registerWithEureka: false

ribbon:
  connectTimeout: 3000
  readTimeout: 10000
